# Generated by Django 4.0.4 on 2022-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday_date',
            field=models.DateField(),
        ),
    ]
